### ISSUE TITLE
Premium SSD disks not deleted together with cluster

### ISSUE THREAD

**Issue by andreas-wilm** [Azure/cyclecloud-beegfs#7]
Hello, I've used the Azure Marketplace CycleCloud image to play with BeeGFS. Whenever I deleted a cluster, the associated Premium SSDs were not deleted (i.e. costs kept growing), while all other resources were removed. Not sure if this is the right place to report this...

Andreas

**Comment by carogonzalezzapata** [comment]
This issue will be fixed in the next release 8.2 (soon!)

**Comment by carogonzalezzapata** [comment]
Fixed in the Azure Portal. Tested today. Closing the case.
